NetworkEnv-v0:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.99
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 2048
  policy_kwargs:
    net_arch:
      pi:
      - 64
      - 64
      vf:
      - 64
      - 64
  vf_coef: 0.5
